mono:
    # parameters
    ros__parameters:
      ros_mono_voc_dir: "/home/mzhang/home_work/orb-slam2/orbslam2_study/Vocabulary/ORBvoc.txt" 
      ros_mono_config_dir: "/home/mzhang/home_work/orb-slam2/orbslam2_study/Examples/Monocular/TUM1.yaml"


